### ISSUE TITLE
Can't figure out how to add an escape block as an observer 

### ISSUE THREAD

**Issue by zeflash** [RxSugar/RxSugar#4]
It's not exactly an issue - but rather a help request :)

I really like the idea being RxSugar in the sense it really clears up the code. Binding variables is cool - but I'd also like to do the equivalent of subscribe(onNext) using <~ without having to assign my block to a variable (like in the example - selectionHandler)

Given the direction of the operator, I would have assumed something like this:
{
 // my block, using $0 
} <~ variableToObserve

Trouble is, I can't figure out how to declare such a block based on the operator declaration, and I can't find an example. My swift isn't good enough yet to figure this out.

**Comment by marksands** [comment]
@zeflash Happy to help. What you have written would more or less work. I think you're trying to accomplish this? Let me know otherwise..

```swift
rxs.disposeBag ++ { [weak self] in self?.backgroundColor = $0 } <~ colorObservable
```

**Comment by zeflash** [comment]
I was missing an asObservable(), was trying to use the Variable directly.

So my initial try should have worked but I wasn't able to understand the build error message :)

Side question - why having things declared in that direction? observer <~observable instead of observable ~> observer ?
Wouldn't it be cleaner visually to have:
disposeBag ++ observableColor ~> { do something with $0 } ?

**Comment by DivineDominion** [comment]
I prefer @zeflash's left-to-right way to write it, too, if anybody cares 😅

**Comment by marksands** [comment]
Feel free to add the operator overload to your project 😄

I forget the exact semantics around the initial conversation, but I believe it stemmed from cribbing the same binding operator from Reactive~Cocoa~_Swift_ https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/UnidirectionalBinding.swift

**Comment by JARinteractive** [comment]
@DivineDominion, @zeflash I and @marksands talked a bit more about the `~>` operator and decided to add it this morning.

**Comment by marksands** [comment]
I finally pushed a new release that includes the `~>` operator. Cheers!
